export enum GameUserStatus {
	notConnected,
	alreadyConnected,
	connected,
	inQueue,
	choosingOptions,
	readyToStart,
	gameCancelled,
	waitingGameStart,
	waitingGameRestart,
	inGame,
	waitingOpponentReconnection,
	disconnectedAfk,
	opponentDisconnected,
	gameWinner,
	gameLoser,
}
