import { useEffect, useState } from "react";
import { useLocation, useNavigate } from "react-router-dom";
import Input from "../../../components/Input/Input";
import { verifyTfaRequest } from "../../../api";

export default function VerifyTfa() {
	const location = useLocation();
	const navigate = useNavigate();
	const [inputValue, setInputValue] = useState<string>("");
	const tmp_accessToken = location.state.accessToken;

	async function handleInputChange(e: React.ChangeEvent<HTMLInputElement>) {
		setInputValue(e.target.value);
	}

	async function handleSubmit() {
		if (inputValue === "") return;
		const verificationCode = inputValue.replace(/\s/g, "");
		try {
			const res = await verifyTfaRequest(verificationCode, tmp_accessToken);
			if (res.ok) navigate("/");
			else {
				const body = await res.json();
				alert(body.message);
				navigate("/login");
			}
		} catch (e) {
			console.error("Error sending qrCode verification values", e);
		}
	}

	useEffect(() => {
		function handleKeyPress(event: KeyboardEvent) {
			if (event.key === "Enter") {
				handleSubmit();
			}
		}
		window.addEventListener("keypress", handleKeyPress);
		return () => {
			window.removeEventListener("keypress", handleKeyPress);
		};
	}, [handleSubmit]);

	return (
		<div className="container d-flex flex-column align-items justify-content">
			<h2 className="underTitle">Verify Two Factor Authentication</h2>
			<p className="d-flex justify-content mb-30 mt-10">
				Enter the code generated by your authenticator app.
			</p>
			<Input
				icon="fa-solid fa-key"
				type="text"
				name="userName"
				placeholder="Ex: 123456"
				value={inputValue}
				onChange={handleInputChange}
			/>
			<div className="d-flex flex-row mt-10">
				<button
					className="btn btn-primary p-5"
					type="submit"
					onClick={handleSubmit}
				>
					Validate
				</button>
				<button
					className="btn btn-reverse-primary ml-10"
					onClick={() => {
						navigate("/login");
					}}
				>
					Bak to login
				</button>
			</div>
		</div>
	);
}
